### PR TITLE
Add emojiPosition to sideTrack component.

### PR DESCRIPTION
**Pull request by rin**
Screen Shot 2019-03-14 at 19 08 17
Screen Shot 2019-03-14 at 19 07 14
Screen Shot 2019-03-14 at 19 06 12
Screen Shot 2019-03-14 at 19 06 08

### CODE REVIEW

**Comment by kbardi** [comment]
Sorry, but the thing here is we already have the SideTrack component in blueprint. The code seems to be right,  so you can merge it, but if it's ok I'm gonna copy this code to blueprint too, and replace the places where we use it from aime-portal :)

**Comment by rin** [comment]
@kbardi Sorry, your comment really confuses me :). Were you already asleep when you wrote it or am I still asleep now? :D We have the sideTrack component in Blueprint and we use it in Portal, right? Or do you mean we have a copy of the component in Portal? 
Anyway, this might need an update because I have to check out how it will work differently on mobile.

**Comment by kbardi** [comment]
> @kbardi Sorry, your comment really confuses me :). Were you already asleep when you wrote it or am I still asleep now? :D We have the sideTrack component in Blueprint and we use it in Portal, right? Or do you mean we have a copy of the component in Portal?
> Anyway, this might need an update because I have to check out how it will work differently on mobile.

Hahahaha, I was asleep!!! Sorry, I read somewhere it was aime-portal, not blueprint! My bad

**Comment by mischacolley** [comment]
@rin wanna get this merged and implemented with blueprint on portal if it isn't already? I wasn't quite sure of the state ...

**Pull request merged**
