### PR TITLE
Feature/add component types and styles

### PR DESCRIPTION
**Pull request by kbardi**
Some updates for Portal.

Please David let me know if you need any other change...
I think the Deprecated tag is quite useful, but I can add more information.

### CODE REVIEW

**Comment by lulen11** [comment]
⚠️⚠️⚠️ We're holding on this PR because @CarolinaPd is currently working on the portal styles and updating blueprint components in there. - ie. No need to roll back to old legacy `Title type` components because Caro will go through and make sure all instances are looking ok with the new styles 🎉

**Comment by CarolinaPd** [comment]
Hey guys, I created a branch called `feature/portal-title-updates ` where I just replaced the **types** on titles to the latest blueprint components.

**blockTitle** became **h1Titles** 
**gradient** became  **h4Title**

The PR of this branch should go against `feat/profile-page-with-steps`, right?

I got tangled up on changing details (menu, paragraph and some other things) and then I realize it didn’t make much sense because I had already created a branch this morning with that purpose. So I left here just title type replacements.

@davidpaley there are some views of the web I can not get into because it's admin territory, let me know f there is a way I can get there to see how it looks like.

**Comment by davidpaley** [comment]
I think we can close this one, right @kbardi ?

**Comment by kbardi** [comment]
I close it because it is updated on Portal so there is no need of it

**Pull request closed without merging**
