### PR TITLE
Staging to Master

### PR DESCRIPTION
**Pull request by lulen11**
Hi @kbardi and friends!

### NB: Latest update to this on 15 January 2020

~Today I created a `staging` branch off `master`... It was a considered decision that came from me merging a couple things in with staging last week that resulted in some tests failing. Then I had some PRs open on Friday that I was hoping to have reviews on today so that I could merge in and continue along. I ended up created this `staging` branch off `master` where there were some builds failing... I then ran some builds - found the errors, amended, and got the tests working locally too. - with some help from @mischacolley - thank you. - and then opened this PR to Master for you to review.~

~Let me know what you think about introducing this master/staging workflow @kbardi. It gives us a chance to merge things in with `staging` and branch off there so that we're not blocked on progressing. And I guess it gives us more reassurance in knowing that our WIP work won't block our teammates on other projects where we're using blueprint versions.~

~Also would be worth noting: Mischa [weighed in on Slack](https://aimementoring.slack.com/archives/GDJCPH517/p1576209160001900) with some more queries and thoughts on this decision.~

# PR for Release v.2.2.0

## 📆 Release Date
The morning of **Thursday, 15 January 2020** AEST Time

## 📌 Changes
- Introduced Staging --> Master workflow
- Refactored & renamed themes setup
- Updated ReadMe
- Refactored & restyled
-- Titles
-- Buttons
-- Inputs
-- Paragraph 
- Made some refactoring changes that included removing legacy component types / styles
-- Button containers 
-- Title types (removed mainTitle, blockTitle, gradientTitle)
- Refactored variables

### Added
- New theme for website titled, "imaginationRainbowTheme" (slug: `rainbow`)

### Fixed
- Test Snapshots 

### Removed
- Light Theme

## 🛫 Pre-Flight Test Document
_Do we need this?_

## 🦟 Issue for Problems found / things to fix
- [ ] ~We realised that the "Luna Emu" font doesn't load in the website unless loaded directly in the website repo through font-face. Might be the same issue on the portal that we need to fix?~ _Think this has been taken care of with work done to buckets in another branch?_ Could someone please confirm?

## 🚥 Verify/Complete Before Release
- [ ] Refactor theme variables in portal - _@carolinaPd is taking care of this (and related below portal updates) currently. We can still release and portal will not update the blueprint version until her work is complete_ 💃
  - [ ] UPDATES NEEDED: 
      - `portal` theme should now be using `plain` theme, 
      - `website` should now be using `rainbow`,
      - `base` theme is used as the backup default & as the wireframing theme to start with as a _base_.
       - `storm` theme is the old purpleStorm website theme that we will keep in case we ever want to use as a style on a project
- [ ] Refactor title components in portal
  - [ ] UPDATES NEEDED:
      - `mainTitle` and `blockTitle` and `h6Title` have been removed. 
      - replace `h6Title` with `h4Title`
      - replace `gradientTitle` with `h1Title` or `h2Title` _(h1 is larger)_
      - replace `blockTitle` and `mainTitle` with `h4Title` or `h5Title` _(both of these are subheading styles. H4 is larger)_
- [ ] check on `paragraph` components in portal - should be fine, but good to check.
- [ ] Make sure we test titles... buttons... form inputs
- [ ] Update CHANGELOG.md 
- [ ] Update env variables 
- [ ] Get a 👍 from 2 people
- [ ] Fix any outstanding issues in ...

### CODE REVIEW

**Comment by davidpaley** [comment]
Hi @lulen11 and @kbardi I made the changes that you suggested here with all the replacement and it breaks the styles of the Portal. Let me show you:

image
image
image

You can check this here: https://github.com/aimementoring/aime-portal/pull/631. 

Please review it before keep going with the release if not one of our project will remain incompatible with the last release

**Comment by lulen11** [comment]
hey @kbardi where are we at with this?

**Comment by mischacolley** [comment]
@lulen11 FYI this was the last comment from @camposcristianeze https://aimementoring.slack.com/archives/GB0V3876H/p1577066125002900

**Comment by kbardi** [comment]
@lulen11 I'm adding some styles and components we removed, but most of the things are ok, so instead of doing a rollback, I will update this PR with some changes and I'll add tomorrow probably the Phone Input, so we can merge this to master and make a release, which will be so helpful!

**Comment by kbardi** [comment]
@mischacolley could you please take a look and test Blueprint is ready to be released? We updated multiple things and we would like to release a new version today to be used from Website

**Comment by lulen11** [comment]
hi @mischacolley @camposcristianeze @davidpaley @rin (only need 2 of you to review but added 4 to get a higher chance of having this done asap 🤞😁) I have edited the release notes in the first comment to reflect where this PR stands now. Please note the updated list of 📌**Changes** which would be the specific elements to check when testing blueprint in your local website & portal projects. Also, I've updated the `README.md` with clear instructions on how to best do that 👏 Thank you!

**Pull request merged**
