### PR TITLE
Feature/storybook

### PR DESCRIPTION
**Pull request by kbardi**
You can see the docs in https://aimementoring.github.io/blueprint/

### CODE REVIEW

**Comment by mischacolley** [comment]
@kbardi is this the PR you demoed where you have Storybook working? If so did we agree with @camposcristianeze that next steps here were to remove styleguidist and then merge the PR? 

I'd also love to assist re getting some colour swatches and a few more style guide elements included.

**Comment by rin** [comment]
Another question … why does nothing ever appear under "Props"? I would expect the Props to appear there …

**Comment by rin** [comment]
Some more things we said in the call
– this will be so helpful for this issue if we have `readonly`, `disabled` etc. as knobs, so we can quickly see all of them working
- I would love real live code editing like in Blueprint
- I think we can lose the "Actions" tab
- maybe think about how to rearrange the tabs in order of importance (also check what's most important for Lara)
- you already know this, but: it would be great to have the "Props" tab working

Then we also discussed where we would like to see text describing a component and how to use it, and I think I'd like to have that in the "Docs" section. I think the "Notes" tab is too easy to overlook and not really useful.

**Comment by rin** [comment]
One more general thing … let's check with @lulen11 about this, but the general UI confused and overwhelmed me a little and I wonder whether we can get closer to something like this: 

https://necolas.github.io/react-native-web/docs/?path=/docs/overview-getting-started--page 

or this

https://gumdrops.gumgum.com/index.html?path=/story/atoms--button

or even this

https://appnexus.github.io/lucid/?path=/docs/controls-button--all-types

I think my main problem is having the two big tabs Canvas and Docs and then all the subtabs for Canvas, plus things like "Show Info" and "Show Code" buttons.

I'm totally happy to help with all of this, and also okay if it's not perfect from the beginning, we can iterate on this. 👏

**Comment by mischacolley** [comment]
@kbardi we don't have a review app here hey? Whats the best way to review running this?

**Comment by kbardi** [comment]
> @kbardi we don't have a review app here hey? Whats the best way to review running this?

You can see it here https://aimementoring.github.io/blueprint/storybook

**Comment by mischacolley** [comment]
@kbardi @rin even though Blueprint future is unsure I'd love to take all the steps we can in the next week or so to get this merged as if things were to continue this would be the path most likely and I'd rather have it merged ....

**Pull request merged**
