### PR TITLE
Conditional title types - ready to be reviewed & merged!

### PR DESCRIPTION
**Pull request by lulen11**
Hey @kbardi 

I started this branch to set up multiple Title types. Eg. h1, h2 etc. That then output different code. Eg. `<h1>Title here</h1>` instead of `<span class="h1">Title here</span>` for each of the types. I tried to figure it out but again having trouble setting it up. Would love to to learn from you :)

### CODE REVIEW

**Comment by lulen11** [comment]
hey @kbardi would love to get some help on this! will reach out to you to schedule a meeting

**Comment by lulen11** [comment]
Hey @kbardi, could you please review and merge this one? We'll come back to styling the titles once we've got more direction from @charliemckenzie but for now, the structure is refactored. 

We're going to use `h1`-`h6` title components rather than `blockTitle` and `mainTitle` - I think naming the components like this will get confusing in the future and best if we start with just the basic `h1`-`h6` :)

**Comment by lulen11** [comment]
Hey @kbardi @rin @davidpaley @charliemckenzie would love to get a couple of reviews on this one so I can merge with master :D

**Comment by rin** [comment]
Code looks good, but this also needs an update of the tests.

**Comment by lulen11** [comment]
> Code looks good, but this also needs an update of the tests.

@kbardi I think you mentioned you knew why these tests are failing, and that it was ok to merge while they fail because you were going to resolve it in master or something... right? 😅

**Comment by lulen11** [comment]
@kbardi :)

**Pull request merged**
