### PR TITLE
Configure video player

### PR DESCRIPTION
**Pull request by rin**
Just a tiny change so far. Don't merge yet.

### CODE REVIEW

**Comment by mischacolley** [comment]
@rin what is that status on this one?

**Comment by mischacolley** [comment]
@rin @davidpaley as flagged here https://github.com/aimementoring/website/issues/836 looking at this as something want to impliment on the website real soon

**Comment by davidpaley** [comment]
Hey @mischacolley. I assumed that you mention this because of Apparel. 

The last time I tested this was not compatible with some video formats that we have in the website. So unless you @rin have found a way to reproduce this kind of videos I would stick with video-js (at least for now).

**Comment by rin** [comment]
@mischacolley David and I are going to review this on Monday and then update this issue!

**Comment by rin** [comment]
So, the status of this is:
• I added react-player and styled it to look kinda … minimalistic . screenshot is here: https://github.com/aimementoring/blueprint/issues/24#issuecomment-480894078
• my main problem with it is that the README of `react-player` says `Due to various restrictions, ReactPlayer is not guaranteed to function properly on mobile devices` (see here https://github.com/CookPete/react-player#mobile-considerations ). It might be that this mainly applies to the youtube and the vimeo player, where `react-player` relies on the SDK of youtube/vimeo, and that it's only about the user having to tap the video so that it starts playing.
• suggestion: we could add react-player to the website to try it out (since we still have issues to integrate blueprint in the website anyway) and find out if it works for us (which would mean we would need to ask some people with different phones to test it). if it does, we can then add it to blueprint (and solve the problem to integrate blueprint into the website!).

**Comment by lulen11** [comment]
@kbardi @rin it looks like we've merged this with master, right? Can we close this one? :)

**Comment by mischacolley** [comment]
@lulen11 can you preview this visually first and play around with style/settings ... from when I last looked at this I assume it would still need work

**Comment by lulen11** [comment]
hey @kbardi i reckon this would be your next best component to work on :)

**Comment by lulen11** [comment]
hey @bronz3beard i know you've been working on this one. is this PR still relevant? What's the status?

**Comment by bronz3beard** [comment]
> hey @bronz3beard i know you've been working on this one. is this PR still relevant? What's the status?

Hey @lulen11 
Not sure about this pr, but there is another pr for `react-player`, [AimeVideoPlayer](https://github.com/aimementoring/blueprint/pull/163).
It is probably better to ask @rin about this one, if this pr gets closed we can just add a link to my pr as reference.

**Comment by rin** [comment]
Yeah, we can close that! It was just important that Rory saw it as a reference :). But even if it's closed, we can always find it again.

**Pull request closed without merging**
