### PR TITLE
Fix: Let people empty date fields.

### PR DESCRIPTION
**Pull request by rin**
I think every one should be able to empty a date field … and I need this for what I do in Portal right now.

Would love to know what was the thinking behind this, it really confused me. :)

### CODE REVIEW

**Comment by davidpaley** [comment]
Rin this is really difficult to explain, but has to do with the strange behaivour of the input with type date. Remember when we click on 0 for the year and it put the field empty and we couldn't change that? the main reason is for example you are completing the date, the onchange function is called when you complete the last field (could be day, month or year), the thing that happened was that when you complete the day, then the month, and after that when you tried to 2020 for the year, when you press 0 for the year it detect that you wanted to put 20 as a year and I don't know why the browser doesn't let you to put that year, so that is why it turns to be an empty value and it reset the value of the full date.

It is really difficult to explain, I could explain this in a call, but we should keep that, if not we are going to start to have this strange behaviour that we had previously. The only way  to resolve this in another way is to add a library for the date, for now I think this is ok. I mean I know it is not the best not being able to put a date to empty but worst is not being able to put any date at all. 

You can actually put an empty date but it will not bee saved in our model in the Portal.

You can confirm what I am saying if you deploy this, test it in portal and try to put for example 11/02/2020 starting with the day (then month, and after that year).

I hope you understand what I am trying to explain..

**Comment by camposcristianeze** [comment]
I marked the fix of the input date as fixed but I agree that from a user perspective we should be able to clear the date. In fact, there's a button for that in most browsers?

**Comment by davidpaley** [comment]
> ?

As a first solution, we could have a button to clear the date.. The problem is if you want to do it just deleting it with the delete key (you can do it but it is not going to be saved (I explained this in my previous comment)). But we can do it with a button..

**Comment by davidpaley** [comment]
> The change looks good to me, but what I would like to do is to find a fix for the situation @davidpaley explained with no need of disabling clean action for the field...I think it should be possible to have an empty date, but maybe we need more time to review this change

This solution broke the whole date picker, I think we should close this PR and think another solution for when we need to clear the date field.

**Comment by rin** [comment]
Yeah, let's close this – it's on my to do list to find/build a new datepicker :)

**Pull request closed without merging**
